# Generated by Django 5.1.4 on 2024-12-13 07:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produce_name', models.CharField(max_length=255)),
                ('organic', models.BooleanField(choices=[(True, 'Organic'), (False, 'Inorganic')], default=True)),
                ('quantity', models.FloatField(help_text='Amount in kilograms or tons')),
                ('expected_harvest_date', models.DateField()),
                ('planting_date', models.DateField()),
                ('description', models.TextField()),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_harvest_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Planted', 'Planted'), ('Growing', 'Growing'), ('Harvested', 'Harvested')], default='Planted', max_length=20)),
                ('status_last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produce', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProduceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/produce_images/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('produce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myApp.produce')),
            ],
        ),
    ]
