# Generated by Django 5.1.4 on 2024-12-13 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_produce_status_cart_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='create_date',
            new_name='created_at',
        ),
    ]
