# Generated by Django 5.1.4 on 2024-12-13 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_remove_billingdetails_create_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_details',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='produce',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='produce',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='produceimage',
            name='produce',
        ),
        migrations.DeleteModel(
            name='BillingDetails',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Produce',
        ),
        migrations.DeleteModel(
            name='ProduceImage',
        ),
    ]
